# This file is a template, and might need editing before it works on your project.
image: golang:1.17

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...

test:
  stage: test
  script:
    - go test -race ./...
